import { useState } from "react"
import DashboardLayout from "../components/layout/DashboardLayout"
import { recommendations } from "../data/mockData"
import { Filter, CheckCircle, Clock, AlertTriangle, Lightbulb } from "lucide-react"

function PriorityBadge({ priority }) {
  const styles = {
    High: "bg-red-50 text-red-600 border border-red-100",
    Medium: "bg-yellow-50 text-yellow-600 border border-yellow-100",
    Low: "bg-green-50 text-green-600 border border-green-100",
  }
  return (
    <span className={`text-xs font-semibold px-3 py-1 rounded-full ${styles[priority]}`}>
      {priority} Priority
    </span>
  )
}

const allRecommendations = [
  ...recommendations,
  {
    id: 5,
    priority: "High",
    title: "Test Soil Nitrogen Levels",
    description: "Nitrogen deficiency suspected on Manga Farm based on leaf color analysis.",
    farm: "Manga Farm",
  },
  {
    id: 6,
    priority: "Low",
    title: "Cover Crop Planting",
    description: "Plant leguminous cover crops to improve soil organic matter after harvest.",
    farm: "Borabu Farm",
  },
  {
    id: 7,
    priority: "Medium",
    title: "Soil Drainage Improvement",
    description: "Install drainage channels to prevent waterlogging during heavy rainfall.",
    farm: "Riana Farm",
  },
]

function Recommendations() {
  const [filter, setFilter] = useState("All")
  const [completed, setCompleted] = useState([])

  const filters = ["All", "High", "Medium", "Low"]

  const filtered = allRecommendations.filter((r) =>
    filter === "All" ? true : r.priority === filter
  )

  function toggleComplete(id) {
    setCompleted((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    )
  }

  return (
    <DashboardLayout pageTitle="Recommendations">

      {/* Page Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-gray-800 text-2xl font-bold">AI Recommendations</h2>
          <p className="text-gray-600 text-sm mt-1">
            Personalized soil management advice generated by SoilSense AI Engine
          </p>
        </div>
        <div className="flex items-center gap-2 bg-green-50 border border-green-100 px-4 py-2 rounded-xl">
          <Lightbulb className="w-4 h-4 text-green-600" />
          <span className="text-green-700 text-sm font-semibold">
            AI Confidence: 84%
          </span>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 mb-6">
        <div className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
          <p className="text-gray-600 text-xs font-semibold uppercase tracking-wide">
            Total
          </p>
          <p className="text-3xl font-bold text-gray-800 mt-2">
            {allRecommendations.length}
          </p>
          <p className="text-gray-600 text-xs mt-1">Recommendations</p>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="w-4 h-4 text-red-500" />
            <p className="text-gray-600 text-xs font-semibold uppercase tracking-wide">
              High Priority
            </p>
          </div>
          <p className="text-3xl font-bold text-red-500 mt-2">
            {allRecommendations.filter((r) => r.priority === "High").length}
          </p>
          <p className="text-red-400 text-xs mt-1">Urgent action needed</p>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <Clock className="w-4 h-4 text-yellow-500" />
            <p className="text-gray-600 text-xs font-semibold uppercase tracking-wide">
              Pending
            </p>
          </div>
          <p className="text-3xl font-bold text-yellow-500 mt-2">
            {allRecommendations.length - completed.length}
          </p>
          <p className="text-yellow-400 text-xs mt-1">Awaiting action</p>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle className="w-4 h-4 text-green-500" />
            <p className="text-gray-600 text-xs font-semibold uppercase tracking-wide">
              Completed
            </p>
          </div>
          <p className="text-3xl font-bold text-green-600 mt-2">
            {completed.length}
          </p>
          <p className="text-green-500 text-xs mt-1">Actions taken</p>
        </div>
      </div>

      {/* Filter and List */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">

        {/* Filter Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-50">
          <h3 className="text-gray-800 font-bold text-base">
            All Recommendations
          </h3>
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-gray-400" />
            {filters.map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`text-xs font-semibold px-3 py-1.5 rounded-lg transition-all ${
                  filter === f
                    ? "bg-[#166534] text-white"
                    : "bg-gray-50 text-gray-600 hover:bg-gray-100"
                }`}
              >
                {f}
              </button>
            ))}
          </div>
        </div>

        {/* Recommendations List */}
        <div className="divide-y divide-gray-50">
          {filtered.map((rec, index) => (
            <div
              key={rec.id}
              className={`px-6 py-5 hover:bg-gray-50 transition-colors ${
                completed.includes(rec.id) ? "opacity-60" : ""
              }`}
            >
              <div className="flex items-start gap-4">

                {/* Number */}
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0 mt-0.5 ${
                  completed.includes(rec.id) ? "bg-green-500" : "bg-[#166534]"
                }`}>
                  {completed.includes(rec.id)
                    ? <CheckCircle className="w-4 h-4" />
                    : index + 1
                  }
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <p className={`text-sm font-bold ${
                      completed.includes(rec.id)
                        ? "line-through text-gray-400"
                        : "text-gray-800"
                    }`}>
                      {rec.title}
                    </p>
                    <PriorityBadge priority={rec.priority} />
                  </div>
                  <p className="text-gray-600 text-xs leading-relaxed mb-2">
                    {rec.description}
                  </p>
                  <div className="flex items-center gap-4">
                    <div className="flex items-center gap-1">
                      <span className="text-green-600 text-xs">🌾</span>
                      <span className="text-gray-600 text-xs font-medium">
                        {rec.farm}
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <span className="text-gray-400 text-xs">🤖</span>
                      <span className="text-gray-500 text-xs">
                        AI Generated
                      </span>
                    </div>
                  </div>
                </div>

                {/* Action Button */}
                <button
                  onClick={() => toggleComplete(rec.id)}
                  className={`shrink-0 text-xs font-semibold px-4 py-2 rounded-xl transition-all ${
                    completed.includes(rec.id)
                      ? "bg-green-50 text-green-600 border border-green-100"
                      : "bg-[#166534] text-white hover:bg-green-800"
                  }`}
                >
                  {completed.includes(rec.id) ? "✓ Done" : "Mark Done"}
                </button>

              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-[#F0FDF4] border-t border-green-100">
          <div className="flex items-center gap-2">
            <span className="text-green-600 text-sm">🤖</span>
            <p className="text-green-700 text-xs font-medium">
              All recommendations are AI-generated and reviewed by a certified extension officer before delivery.
            </p>
          </div>
        </div>

      </div>

    </DashboardLayout>
  )
}

export default Recommendations