import { recommendations } from "../../data/mockData"

function PriorityBadge({ priority }) {
  const styles = {
    High: "bg-red-50 text-red-600 border border-red-100",
    Medium: "bg-yellow-50 text-yellow-600 border border-yellow-100",
    Low: "bg-green-50 text-green-600 border border-green-100",
  }

  return (
    <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${styles[priority]}`}>
      {priority}
    </span>
  )
}

function RecommendationsPanel({ aiRecommendations }) {
  const displayRecommendations = aiRecommendations || recommendations
  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden h-full">

      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-gray-50">
        <div>
          <h3 className="text-gray-800 font-bold text-base">AI Recommendations</h3>
          <p className="text-gray-400 text-xs mt-0.5">Generated by SoilSense AI Engine</p>
        </div>
        <button className="text-[#166534] text-sm font-semibold hover:text-green-700 transition-colors">
          View All →
        </button>
      </div>

      {/* Recommendations List */}
      <div className="divide-y divide-gray-50">
        {displayRecommendations.map((rec, index) => (
          <div
            key={rec.id}
            className="px-6 py-4 hover:bg-gray-50 transition-colors cursor-pointer"
          >
            <div className="flex items-start gap-4">

              {/* Number */}
              <div className="w-7 h-7 rounded-full bg-[#166534] flex items-center justify-center text-white text-xs font-bold shrink-0 mt-0.5">
                {index + 1}
              </div>

              {/* Content */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <p className="text-gray-800 text-sm font-semibold">{rec.title}</p>
                  <PriorityBadge priority={rec.priority} />
                </div>
                <p className="text-gray-500 text-xs leading-relaxed">{rec.description}</p>
                <div className="flex items-center gap-1 mt-2">
                  <span className="text-green-600 text-xs">🌾</span>
                  <span className="text-gray-400 text-xs">{rec.farm}</span>
                </div>
              </div>

            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="px-6 py-4 bg-[#F0FDF4] border-t border-green-100">
        <div className="flex items-center gap-2">
          <span className="text-green-600 text-sm">🤖</span>
          <p className="text-green-700 text-xs font-medium">
            AI confidence average: <span className="font-bold">84%</span> — All recommendations reviewed by extension officer
          </p>
        </div>
      </div>

    </div>
  )
}

export default RecommendationsPanel